 /* SAS Mini Project*/
/* Should showcase:
do loops-check
macros
if then-check
DATA STEP-check
PROC SQL-check
Analysis skills.
*/

/*Practice*/
proc sql outobs=5;
	create table sasplay.garlic_5 as
	select * from sasplay.garlic;
quit;

proc sql outobs=5;
	create table sasplay.garlic_5 as
	select BedID, Fertilizer from sasplay.garlic;
quit;

/* Create new dataset and add new column using do loop*/
proc sql outobs=20;
	create table sasplay.garlic_20 as
	select * from sasplay.garlic;
quit;

data sasplay.garlic_20;
	set sasplay.garlic_20;
	do i=1 to 20 by 1;
		new_col = i*2;
	output;
	end;
run;

/*Perhaps can join some country-level TB data by ISO3?*/

proc import datafile='/home/u49098581/SASplay/2016 estimates_v3.csv'
	dbms=csv
	out= sasplay.tbidata2016;
run;

proc import datafile='/home/u49098581/SASplay/TB burden country copy.csv'
	dbms=csv
	out= sasplay.tb_inc;
run;

proc sql outobs=30;
	select * from sasplay.tbidata2016;
quit;

proc sql;
	create table sasplay.tb_inc_selected as
	select country,iso3, g_whoregion, year, e_inc_100k 
	from sasplay.tb_inc
	where year=2016;
quit;

/* Merge the datasets together. Could use joins in proc sql or merge in DATA step */
/* if-then to create new incidence band categories*/

data sasplay.tb_merged;
	merge sasplay.tbidata2016 sasplay.tb_inc_selected;
	by = iso3;
	length inc_band $ 12;
	if e_inc_100k <50 then inc_band = "0-49";
	else if e_inc_100k <100 then inc_band = "50-99";
	else if e_inc_100k <200 then inc_band = "100-199";
	else inc_band = "200+";
run;


/* Creating a macro that analyzes association between TBI and other predictor variables for input countries.
Note: This data is used to learn and explore data manipulation techniques as well as 
GLM models with real world data. However, this data was fit with a Bayesian model in the 
real world, all countries were included as parameters, and used additional parameters that 
I cannot include at this time due to memory run-time constraints. Thus, these models do not fit the data
well, but still serve as an opportunity to examine how to model and how to understand what factors
lead to models being a not so good fit.*/

%macro by_country_analysis(country);

	proc sql;
		create table sasplay.model_tab as
		select iso3, YOBP, YARP, LTBP, NUMP
		from sasplay.tb_merged
		where iso3="CHN";
	quit;	
	
	data sasplay.model_tab;
		set sasplay.model_tab;
		LTBP = ROUND(LTBP);
		NUMP = ROUND(NUMP);
	run;
	
	/* Use this to show that distribution is skewed to the right, and showing that poisson is most approprioate for this data, 
	but interestingly bimodal for China*/
	proc sgplot data=sasplay.model_tab;
		histogram LTBP;
		density LTBP;
		density LTBP/type=kernel;
	run;
	
	/* We see that data is overdispersed as value/df is much greater than 1. 
	May not be able to trust type3 stats*/
	/*ods select moments basicmeasures;
	proc univariate data=sasplay.model_tab;
		var LTBP;
	run;*/
	
	/* Poisson*/
	/*proc genmod data = sasplay.model_tab plots=all;
  		model LTBP = NUMP YARP/dist=poisson link=log type3;
  		store p1; 
  	run;*/
  	
  	/* Negative Binomial*/
  	/* We see that AIC is lower for this model compared to Poisson but still not a good fit.
  	Dispersion parameter a little far from zero, indicating that overdispersion was, indeed, a problem
  	with the Poisson model. While diagnostic plots can easily be generated by adding the 'diagnostics'
  	option, it will simply yield plots that once again demonstrate that the model
  	in this form is not a good fit for the data.*/
  	
  	ods graphics/reset=all imagemap=on;
  	proc genmod data = sasplay.model_tab plots(unpack)=all;
  		model LTBP = NUMP YOBP YARP/dist=negbin link=log type3 ;
  		store p2; 
  	run;

%mend;

%by_country_analysis(country ='CHN')
